const crawlers = new Map()
crawlers.set('au-tattslotto', [require('./latest/tattsLottoCrawler')])
crawlers.set('au-oz-lotto', [require('./latest/ozLottoCrawler')
//  ,require('./bak/ozLottoCrawler')
])
crawlers.set('au-powerball', [require('./latest/powerBallCrawler')
//, require('./bak/powerBallCrawler')
])
crawlers.set('au-set-for-life', [require('./latest/setForLifeCrawler')
//, require('./bak/setForLifeCrawler')
])
crawlers.set('au-mon-wed-lotto', [require('./latest/monWedLottoCrawler')
//, require('./bak/monWedLottoCrawler')
])
crawlers.set('au-super-66', [require('./latest/super66Crawler')
//, require('./bak/super66Crawler')
])

module.exports = crawlers
