# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint

    # Slack 通知
    - name: Slack Success Notification
      if: success()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: 爬虫新的提交在 ${{ matrix.node-version }} 检查通过
        SLACK_ICON_EMOJI: robot_face
        SLACK_USERNAME: Lotto Config Bot
        SLACK_CHANNEL: dev

    - name: Slack Failure Notification
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: 爬虫新的提交在 ${{ matrix.node-version }} 语法检查未通过
        SLACK_ICON_EMOJI: robot_face
        SLACK_USERNAME: Lotto Config Bot
        SLACK_COLOR: "#ff5f52"
        SLACK_CHANNEL: dev
